version: "3"
services:
  db:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mysecretpassword
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=fullstack
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - shared-network
  
  api:
    container_name: node-api
    build:
      context: server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - 8080:8080
    networks:
      - shared-network
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:3306

  client:
    container_name: react-client
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 4200:3000
    networks:
      - shared-network
    depends_on:
      - api 

networks:
  shared-network:

volumes: 
  my-db: