version: "3"
services:
  db:
    image: mysql
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=fullstack
    volumes:
      - ./mysql-db/data
    networks:
      - shared-network
  
  api:
    container_name: node-api
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - shared-network
    depends_on:
      - db

  client:
    container_name: react-client
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    networks:
      - shared-network
    depends_on:
      - api

networks:
  shared-network: