version: "3"
services:
  db:
    container_name: mysqldb
    image: mysql/mysql-server:8.0.23
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: fullstack
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./mysql-data/8.0.23:/var/lib/mysql
    ports:
      - 3307:3306
    expose:
      - 3307